### ISSUE TITLE
Issues to be solved for TadHack

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty-toolkit#19]
This issues is created to collect most priority issues to be addressed for the [Hackathon (14-16 Oct)](http://tadhack.com/2016/):

- [x] [toolkit crashes with hyperty bugs](#21) 
- [ ] [timeout](https://github.com/reTHINK-project/dev-hyperty/issues/30) 
- [x] [login popup block](https://github.com/reTHINK-project/dev-runtime-browser/issues/56)
- [ ] https://github.com/reTHINK-project/dev-hyperty/issues/35 - reject calls by connector
- [x] [Add listeners to Vertx for subscribe messages](https://github.com/reTHINK-project/dev-msg-node-vertx/issues/24)
- [x] [domain registry / connector bug](https://github.com/reTHINK-project/dev-msg-node-vertx/issues/23)
- [ ] [NodeJS availability for server side Hyperties eg Carrefour Tickets Reporter](https://github.com/reTHINK-project/dev-runtime-core/issues/110)
- [x] [Quobis Group Chat](https://github.com/reTHINK-project/dev-hyperty/issues/42)
- [ ] [User Status](https://github.com/reTHINK-project/dev-hyperty/issues/41)
- [x] [Location](https://github.com/reTHINK-project/dev-hyperty/issues/40)

**Comment by pchainho** [comment]
Done
